# include board common
include $(RIOTBOARD)/common/silabs/Makefile.include

FLASHFILE ?= $(BINFILE)

PROGRAMMER = xdk-workbench

PROGRAMMERS_SUPPORTED += xdk-workbench

ROM_START_ADDR = 0x00020000 # Depends on Bootloader
